Repository Clueless-Community/first-contribution, pull requests merged in 2022-10, with the labels that each got.

#299 added socials section in footer
  pages/components/Footer.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#304 added my data
  Contributors.md
  data/contributors.js
Labels: hacktoberfest-accepted

#405 changed data and Contributors.md
  Contributors.md
  data/contributors.js
Labels: good first issue, hacktoberfest-accepted

#377 Added my data
  data/contributors.js
Labels: good first issue, hacktoberfest-accepted

#506 Added my name
  Contributors.md
  data/contributors.js
Labels: merged

#492 Added my data
  Contributors.md
  data/contributors.js
Labels: merged

#484 Added new contributor
  data/contributors.js
Labels: merged

#558 added my data
  Contributors.md
Labels: merged
